artifacts_root: artifacts

data_ingestion:
                root_dir: artifacts/data_ingestion
                source_URL: https://github.com/JanvitaReddy11/Red-Wine-Quaility-Prediction/raw/main/archive.zip
                local_data_file: artifacts/data_ingestion/data.zip
                unzip_dir: artifacts/data_ingestion

data_validation: 
                root_dir: artifacts/data_validation
                unzip_data_path: artifacts/data_ingestion/WineQT.csv
                status_file: artifacts/data_validation/status.txt




                

