artifacts_root: artifacts

data_ingestion:
root_dir: artifacts/data_ingestion
source_url: https://github.com/JanvitaReddy11/Red-Wine-Quaility-Prediction/raw/main/archive.zip
local_data_file: artiacts/data_ingestion/data.zip
unzip_dir: artifacts/data_ingestion
